### GET published posts
GET http://localhost:8000

### GET all posts
GET http://localhost:8000/all

### POST create post
POST  http://localhost:8000
Content-Type: application/json

{
  "title": "smt",
  "body": "body"
}

### DELETE delete post
DELETE  http://localhost:8000/17

### DELETE delete post 1
DELETE  http://localhost:8000/id/18