[package]
name = "starter-rest"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
starter-data = { path = "../starter-data" }
serde = { version = "1.0", features = ["derive"] }